Week1/signin signup home(1주차 과제 코드리뷰)
8-seconds/mdb1217_BESOPTAssignment pull request #9
Opened 2021-04-09 20:52 UTC by mdb1217

## 1주차 과제 주요 포인트
- MVVM 아키텍처
- 로컬 저장소 Room, SharedPreference 사용
- DI(힐트)
- 애니메이션(페이드 인)
- UI 아주 이쁨(중요)
- 미세먼지 만큼 코루틴...?이라고도 못 부를 비동기처리

<img src="https://user-images.githubusercontent.com/70698151/114239000-70319400-99c0-11eb-8823-7e757f8e8f0c.png" width="200px"/>

<img src="https://user-images.githubusercontent.com/70698151/114239111-9820f780-99c0-11eb-8b9b-6caca8cd3dbe.png" width="200px"/>

<img src="https://user-images.githubusercontent.com/70698151/114239176-b1c23f00-99c0-11eb-8eeb-b99a2dc2e33b.png" width="200px"/>

2021-04-11 16:40 UTC, yjooooo commented
다빈아 너 과제에 진심이구나 대박이야

2021-04-11 16:50 UTC, l2hyunwoo requested changes
간략하게 리뷰했습니다. Coroutine 부분이 조금 어려울텐데 그래도 써봤으니 다음에 더 잘 쓸 수 있을 거하 믿습니다 홧팅

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/data/local/SOPTSharedPreference.kt
> +        preferences.edit().putBoolean(ID_PASSWORD_EXIST, value).apply()
안드로이드 KTX를 쓰면 조금 더 깔끔하게 작성 가능함
```suggestion
        preferences.edit { putBoolean(ID_PASSWORD_EXIST, value) }
```

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/data/local/database/UserDatabase.kt
> +        }
아래에 Database 모듈에서 DB를 만들텐데 굳이 여기서 싱글턴 객체를 만드는 함수를 넣을 필요가 있을까?

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/data/repository/UserRepoImpl.kt
> +        }
오우....
- runBlocking은 어떤 위험을 가져올까? 
- 코루틴을 왜 사용할까? 원래의 비동기 처리방식은 어떤 문제점을 가졌고 이를 어떻게 해결했을까?
이 부분을 다시 한번 알아보면 좋을 것 같아

[runBlocking 관련 글](https://thdev.tech/kotlin/2020/12/15/kotlin_effective_15/)이니까 참고해서 읽어봐

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/data/repository/UserRepoImpl.kt
> +        }
그리고 GlobalScope은 어떤 코루틴을 만들까?

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/di/ApplicationController.kt
> +        SOPTSharedPreference.init(applicationContext)
아 그리고 DI(Hilt)를 쓰는거면 ApplicationContext는 @ApplicationContext로 주입받을 수 있어

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/MainActivity.kt
> +        Glide.with(this).load(R.drawable.img_dabin).circleCrop().into(binding.ivOwner)
DataBinding을 활용한다면 BindingAdapter를 활용해서 View에서 코드 작성양을 줄일 수 있을 것 같아

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/base/BaseActivity.kt
> +    open val viewModel: R by lazy { viewModel }
ViewModel을 Base로 감싼 것에 대한 이유가 있어? 지금 BaseViewModel에 어떠한 내용도 없는 것 같아서

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/di/DatabaseModule.kt
> +}
👍

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/base/BaseFragment.kt
> +    open val viewModel: R by lazy { viewModel }
이부분은 드래그가 여기밖에 안되니까 여기서 리뷰할게

- 우선 initView, initBeforeBinding, initAfterBinding으로 역할을 구분해놨다는 것은 좋다고 생각해, 어찌보면 기능 분리를 해놨다고 생각할 수 있으니까
- binding의 생명주기를 고려해보면서 binding 객체를 설계해보자

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +        }
이런 부분은 DataBinding으로 충분히 색 조정이 가능할 수 있을 것 같아

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +            val password = binding.etPassword.text.toString()
데이터를 처리하는게 과연 뷰의 역할일까? 역할이 많아진다는 것, 제한된다는 것이 어떤 의미를 가지고 왜 선임개발자들이 아키텍처를 사수해야한다라고 말을 했는 지 생각을 해보면 좋을 것 같아

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/data/repository/UserRepoImpl.kt
> +                        setIdPasswordExist(false)
데이터베이스에서 회원정보를 찾는 로직까지는 좋은데 여기서 결과를 SharedPreference에 저장시키는 건 좀 어색한 것 같아, 결과값만 보내도 충분히 로그인이 가능할 것 같은데 어디서나 접근할 수 있는 곳에다가 굳이 필요없는 데이터를 하나 더 추가시키는 것 같아. 이미 자동로그인 여부도 auto login 변수에다 저장시킨 것으로 알고 있는데 ID_PASSWORD_EXIST는 어떤 책임이 있는지 불분명한 것 같아.

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/MainActivity.kt
> +        binding.line.startAnimation(setFadeInAnim(R.anim.fade_in_1500))
👍

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +    private val requestActivity = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { activityResult ->
requestActivity라....Activity에다가 "어떤걸"요청하는 거 아닐까? 그런 부분에서 변수가 표현하려는 의도가 불명확한 것 같아

2021-04-11 16:50 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignUpActivity.kt
> +                val password = binding.etPassword.text.toString()
이런 경우에는 id, name만 채우고 password를 안 채웠을 때 그냥 통과하지 않을까?

2021-04-11 17:08 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/data/local/SOPTSharedPreference.kt
> +        preferences.edit().putBoolean(ID_PASSWORD_EXIST, value).apply()
이야.. 안드파트 끝판왕이 오셨군요.. 코드 리뷰 받게되서 영광입니다.. 감동받아서 손 발이 부들거리네요 ㅋㅋㅋㅋㅋㅋㅋ(화난거 아님) 암튼 **Android Extension** 어려워서 잘 손이 안가게 되던데 확실히 앞으로는 도전해봐야 될 것 같아요.. 현우님이 수정해주신 코드가 정말 훨씬 깔끔해보이네요..! 수정해보겠습니다

2021-04-11 17:10 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/data/local/database/UserDatabase.kt
> +        }
아뇨.. 안그래도 지금 이 코드의 경우 의존성 주입(그니까 힐트를 완전적용시켜서 데이터베이스 모듈 만들기 전)을 넣기전에 만들고 삭제하지않은 코드라서 **불필요하게 중복되는 코드**가 맞습니다.. 지금 안스켜서 들어가보니까 unused code라고 회색빛돌고 삭제하라고 난리치네요 ㅋㅋㅋㅋㅋㅋ 삭제 바로 드갑니다..

2021-04-11 17:13 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/data/repository/UserRepoImpl.kt
> +        }
으악.. 안그래도 runBlocking에 대해서 이전에도 한 번 지적을 받은 적이 있었죠..(메인 스레드를 정지시킬 위험이 있음 그러면 앱이 펑펑퍼러버러펑펑펑~) 사실 제가 코루틴을 제대로 공부하고 적용해본 것은 아니고, runBlocking을 쓴 이유는 join() 메소드를 너무 쓰고 싶어서 예제를 찾아봤는데 예제 코드를 짜신 분이 runBlocking을 써서 자연스럽게 줘도 runBlocking으로 감싸 줬던 것 같아요.. 밑에 2개의 질문은 제대로 공부하고 빠르게 답변 달겠습니다..😂😂

2021-04-11 17:15 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/di/ApplicationController.kt
> +        SOPTSharedPreference.init(applicationContext)
진짜 좋은 정보군요.. Hilt 어노테이션이 강력하긴 하네요.. 오만데 다 쓰이는 것 같고 ㅋㅋㅋ 근데 존나 어렵긴 하더라구요.. 어노테이션 종류들 빡세게 공부해서 돌아오겠습니다.. 아직도 Installin, EntryPoint에서도 발작하는 저 자신이 밉네요

2021-04-11 17:19 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/MainActivity.kt
> +        Glide.with(this).load(R.drawable.img_dabin).circleCrop().into(binding.ivOwner)
하긴 지금 제 코드 대충 보시면 알겠지만.. DataBinding 적용해놓고 진짜 Data layout만 만들어 놓고 BindingAdapter를 전~~~~혀 활용을 안한 상태라서 ㅋㅋㅋㅋㅋㅋ 한 번 시도 해보겠습니다

2021-04-11 17:22 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +            val password = binding.etPassword.text.toString()
제가 아는 MVVM 아키텍처의 경우
- 뷰에서는 UI를 그리는 작업을 한다
- ViewModel에서는 데이터를 처리하는 작업을 한다
- Model에서는 데이터를 저장하는 저장소 같은 역할을 한다
이렇게 알고 있거든요? toString()을 처리 한 부분이 데이터를 처리하는 작업으로 인식이 되는건가요? (사실 잘 모르겠음..)우선  뷰에서 **작업이 많아지지 않아야 한다는 점은 새겨 듣겠습니다!!**

2021-04-11 17:24 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/data/repository/UserRepoImpl.kt
> +                        setIdPasswordExist(false)
preference까지 굳이 데이터를 저장할 필요없이, 바로 뷰모델에서 boolean 값으로 로그인 성공 여부만 알려주면 된다는 말씀이군요..! 참고하겠습니다👍

2021-04-11 17:25 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/MainActivity.kt
> +        binding.line.startAnimation(setFadeInAnim(R.anim.fade_in_1500))
ㅋㅋㅋㅋㅋㅋㅋ 홈 액티비티에 넣을 거 없나해서 심심해서 애니메이션 한 번 적용시켜봤습니다 😂😂

2021-04-11 17:27 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +    private val requestActivity = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { activityResult ->
아..! 저도 남들 변수명 여포(?)로 지적질하고 다녔는데.. 저 자신도 저런 애매모호한 변수를 썼군요.. 반성하겠습니다 지금 SignInActivity의 경우 SignUpActivity에서 **id와 password** 정보를 요청하는 것이므로 그와 관련된 변수 네임으로 변경하도록 하겠습니다 :)

2021-04-11 17:29 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignUpActivity.kt
> +                val password = binding.etPassword.text.toString()
잉 password도 안채워지면 일단 통과는 안되는 것 같습니다..!

2021-04-11 17:32 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/base/BaseActivity.kt
> +    open val viewModel: R by lazy { viewModel }
사실 별다른 의미는 없고 앱잼팀에서 코드 짤 때 Base 클래스를 상속받고 코드를 짜는 게 습관이 되서 저렇게 했는데, 별 의미없는 코드라서 바로 ViewModel 상속받아서 코드 짜도 별 차이는 없을 것 같긴합니다..😂😂

2021-04-11 17:32 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/di/DatabaseModule.kt
> +}
아 비미 힐트 맛집이더라 ^^

2021-04-11 17:34 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/base/BaseFragment.kt
> +    open val viewModel: R by lazy { viewModel }
아..! 하긴 이번 세미나에서도 **binding의 생명주기로 파트장님이 정말정말 강조를 많이 해주셨지..!** 지금 내 코드의 경우 **좀비 객체가 생길 수 있는 위험이 있다고 생각해..** 얼른 고쳐야겠어..

2021-04-11 17:37 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +        }
궁금하니까 한 번 찾아봐야겠다.. 처음에는 selector 쓸려고했는데, 생각해보니 내가 지금 color처리를 해놓은게 constraintLayout이라서 셀렉터 처리가 좀 애매하긴 하더라구.. 그래서 일단 임시방편으로 저렇게 짰는데.. 개인적으로 DataBinding에 ? 삼항 연산자가 된다면 나 진짜 데이터 바인딩에 뼈묻을 자신 있기때문에 한 번 찾아봐야겠다..ㅋㅋㅋㅋ 아니면 Resource ID 값으로 조절해주는 방법도 가능하려나? 한 번 일단 다 시도해보겄으..

2021-04-12 00:15 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/base/BaseActivity.kt
> +    open val viewModel: R by lazy { viewModel }
Base가 어떤 작업을 처리하지? BaseViewModel은 너의 ViewModel에서 어떤역할을 맡아? 역할이 명확하게 구분되어있지 않은 클래스는 다른 개발자가 볼 때 혼란을 줄 수 있어.

2021-04-12 00:20 UTC, l2hyunwoo commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignInActivity.kt
> +            val password = binding.etPassword.text.toString()
아래 부분까지 내가 드래그를 했어야했는데, 결국엔 Data를 변수로 받아와서 조건문에 이를 활용한 로직이 있는거자나? View에서 과연 이런 로직이 필요한가 싶어. 너가 생각하는 View의 역할은 UI를 그린다고 했는데 과연 View는 UI를 그리는 역할만 존재할까? 책임을 구체화해서 생각을 하면 더 좋을 것 같아

2021-04-12 05:23 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/base/BaseActivity.kt
> +    open val viewModel: R by lazy { viewModel }
그런 생각 까지는 하지 못했네.. **BaseViewModel** 을 상속받는다고 해서 각각의 뷰모델이 공통적으로 가질 부분도 딱히 없을 것 같으니..😥😥 오빠 덕분에 역할의 명확한 분리가 얼마나 중요한 지 새삼 깨닫고 간다👍👍

2021-04-14 04:09 UTC, You-jeong136 reviewed
디자인도 엄청 신경 쓰고, DB도 적용해서 인지 과제 코드 보면서 와... 대단하다! 라고 하면서 코드 봤어요. 제가 부족해서 인지 코드에 대해서 제가 리뷰를 한다기 보다는 이런 식으로도 코드를 짤 수 있구나 이런 것도 있구나 하고 감탄만 하고 갑니다... 많이 배워가요!!!!

2021-04-17 07:16 UTC, WonJoongLee commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignUpActivity.kt
>      }
```suggestion
    private fun isAllEditTextEmpty() = isEtNameEmpty() || isEtIdEmpty() || isEtPassword()
```
이렇게 한 줄로도 작성 가능할 것 같습니다!!

2021-04-17 07:33 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/ui/view/user/SignUpActivity.kt
>      }
return 한 줄이면 `=` 써서 적는게 좀 더 깔끔하긴하죵 :) 좋은 리뷰 감사합니다 👍

2021-04-17 08:40 UTC, mdb1217 commented on AndroidAssignment/app/src/main/java/org/sopt/data/repository/UserRepoImpl.kt
> +        }
이번 주 내내 뭐한다고 완전 뒷북이긴한데, 드디어 코루틴 스코프에 대해서 저도 태환님 블로그에서 글들 많이 찾아보고 공부한 결과 답을 알아냈습니다. 우선...
- UI 스레드에서 runBlocking을 호출할 경우 **ANRs** 가 심한 경우 호출될 수도 있고(3초이상 멈추면 앱이 터짐)
- 원래의 비동기 처리 방식의 경우 백그라운드로 내려갔을 때 동작을 보증하지 않는다는 문제점이 있다는 점.
- GlobalScope의 경우 우선 싱글톤이기 떄문에, 프로그램 전체에 악영향을 미칠 수 있다는 점.. 그리고 top-level에서 동작하는 코루틴이기 때문에, application의 라이프사이클 동안 동작하는데, 각각의 화면과 무관하게 종료된다는 점이 있다고 하더라구요.. 그래서 함부로 GlobalScope를 잘 사용하지는 않는다고 되어있더라구요..!

이 리뷰 덕분에 코루틴에 대해서 다시 한 번 생각해볼 수 있는 기회를 가졌던 것 같아요.. 앞으로 좀 더 열심히 찾아보고 공부하겠습니다😊😊

2021-04-19 11:55 UTC, merged

2021-04-21 08:57 UTC, ho-taek reviewed
코드 쓰신 것을 보고 큰 자극을 느꼈어요! 쓰신거 보고 덕분에 Viewmodel이라는 것을 찾아보고 다음 과제때 적용해서 써보도록 하겠습니다. 고생하셨어요~~~